REDIS_HOST: "10.80.49.3:6379"
DB_HOST: "10.80.48.5"
JKF_CLI_HOST: "www.jkf.io"
RUNMODE: "dev"
CF_SERVICE_ACCOUNT: "direct-api-access@lc-pan.iam.gserviceaccount.com"
ENTRYPOINT: "EntryPoint"
PROJECT_ID: "lc-pan"
STORAGE_PROJECT_ID: "lc-shared-public-storage"
TRIGGER_RESOURCE: "lc-public-storage-dev"
STORAGE_ENTRYPOINT: "StorageEntryPoint"
StorageTriggerFuncName: "pan-avatar-delegate"
LegacyEventTopic: "pan_registered_dev"
EventTopic: "pan_event_dev"
