steps:
#  You can refer to secrets only in the args field of a build step.
  - name: 'gcr.io/cloud-builders/go:debian-1.16'
    entrypoint: 'bash'
    args: ['-c', './.cloudbuild/script/build.sh $$GH_TOKEN']
    env:
      - 'BRANCH_NAME=$BRANCH_NAME'
    secretEnv: ['GH_TOKEN']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['.cloudbuild/script/deploy.sh']
    env:
      - 'BUILD=$BUILD_ID'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'PROJECT_NUMBER=$PROJECT_NUMBER'
      - 'REV=$REVISION_ID'
      - 'BRANCH_NAME=$BRANCH_NAME'
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'build', '-t', 'gcr.io/PROJECT_ID/IMAGE_NAME', '--build-arg', 'GITHUB_TOKEN=$$GH_TOKEN', '.' ]
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    args:
#      - gcloud
#      - functions
#      - deploy
#      - FUNCTION_NAME
#      - --region=FUNCTION_REGION
#      - --source=.
#      - --trigger-http
#      - --runtime=RUNTIME
#serviceAccount: 'projects/PROJECT_ID/serviceAccounts/SERVICE_ACCOUNT'
availableSecrets:
  secretManager:
    - versionName: projects/lc-pan/secrets/GH_TOKEN/versions/latest
      env: GH_TOKEN
options:
  logging: CLOUD_LOGGING_ONLY